package ru.ruscrafting.trails.storage

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import java.nio.file.Files
import java.util.UUID

class PlayerPreferencesStoreTest :
    FreeSpec({
        "loads and preserves the legacy players.yml shape" {
            val folder = Files.createTempDirectory("trails-players-")
            val first = UUID.fromString("11111111-1111-1111-1111-111111111111")
            val second = UUID.fromString("22222222-2222-2222-2222-222222222222")
            try {
                Files.writeString(
                    folder.resolve("players.yml"),
                    """
                    players:
                      $first:
                        enable: false
                      $second:
                        boost: true
                    """.trimIndent(),
                )

                PlayerPreferencesStore(folder).use { store ->
                    store.get(first).trailsEnabled(default = true) shouldBe false
                    store.get(first).boostEnabled(default = false) shouldBe false
                    store.get(second).trailsEnabled(default = true) shouldBe true
                    store.get(second).boostEnabled(default = false) shouldBe true
                    store.setBoost(first, true)
                }

                PlayerPreferencesStore(folder).use { reloaded ->
                    reloaded.get(first) shouldBe PlayerPreferences(enabled = false, boost = true)
                    reloaded.get(second) shouldBe PlayerPreferences(enabled = null, boost = true)
                }
            } finally {
                folder.toFile().deleteRecursively()
            }
        }

        "ignores malformed UUID entries instead of losing valid preferences" {
            val folder = Files.createTempDirectory("trails-players-")
            val uuid = UUID.fromString("33333333-3333-3333-3333-333333333333")
            try {
                Files.writeString(
                    folder.resolve("players.yml"),
                    """
                    players:
                      not-a-uuid:
                        enable: false
                      $uuid:
                        enable: true
                        boost: false
                    """.trimIndent(),
                )

                PlayerPreferencesStore(folder).use { store ->
                    store.snapshot().keys shouldBe setOf(uuid)
                    store.get(uuid) shouldBe PlayerPreferences(enabled = true, boost = false)
                }
            } finally {
                folder.toFile().deleteRecursively()
            }
        }

        "migrates the legacy comment-only default file" {
            val folder = Files.createTempDirectory("trails-players-")
            val uuid = UUID.fromString("44444444-4444-4444-4444-444444444444")
            try {
                Files.writeString(folder.resolve("players.yml"), "## DO NOT EDIT THIS FILE\n")

                PlayerPreferencesStore(folder).use { store -> store.setEnabled(uuid, false) }

                PlayerPreferencesStore(folder).use { reloaded ->
                    reloaded.get(uuid).enabled shouldBe false
                }
            } finally {
                folder.toFile().deleteRecursively()
            }
        }
    })
